name: di
version: 3.3.5+1
authors:
- Vojta Jina <vojta.jina@gmail.com>
- Pavel Jbanov <pavelgj@gmail.com>
- Anting Shen <shenantingtt@gmail.com>
- Misko Hevery <misko@hevery.com>
- Victor Berchet <victor@suumit.com>
description: Dependency Injection framework
homepage: https://github.com/angular/di.dart
environment:
  sdk: '>=1.6.0'
dependencies:
  analyzer: '^0.27.0'
  barback: '>=0.15.0 <0.16.0'
  code_transformers: '^0.3.1'
  path: ">=1.3.0 <2.0.0"
dev_dependencies:
  benchmark_harness: ">=1.0.4 <2.0.0"
  guinness: '>=0.1.16 <0.2.0'
  matcher: '>=0.11.0 <0.13.0'
transformers:
- di/module_transformer
